//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AppointmentTable
{
    public int AppointmentId { get; set; }
    public string PatientUserName { get; set; }
    public string DoctorUserName { get; set; }
    public System.DateTime DateAndTime { get; set; }
    public string Description { get; set; }
    public bool Confirmed { get; set; }
}

public partial class DepartmentTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DepartmentTable()
    {
        this.DoctorTables = new HashSet<DoctorTable>();
    }

    public int DepartmentId { get; set; }
    public int HospitalId { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DoctorTable> DoctorTables { get; set; }
    public virtual HospitalTable HospitalTable { get; set; }
}

public partial class DoctorTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DoctorTable()
    {
        this.PatientTables = new HashSet<PatientTable>();
    }

    public int DoctorId { get; set; }
    public int DepartmentId { get; set; }
    public string UserName { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }

    public virtual DepartmentTable DepartmentTable { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PatientTable> PatientTables { get; set; }
}

public partial class HospitalTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HospitalTable()
    {
        this.DepartmentTables = new HashSet<DepartmentTable>();
    }

    public int HospitalId { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Phone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DepartmentTable> DepartmentTables { get; set; }
}

public partial class MessageTable
{
    public int MessageId { get; set; }
    public string UserNameTo { get; set; }
    public string UserNameFrom { get; set; }
    public string MessageSubject { get; set; }
    public string MessageBody { get; set; }
    public System.DateTime Date { get; set; }
}

public partial class PatientTable
{
    public int PatientId { get; set; }
    public int DoctorId { get; set; }
    public string UserName { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }

    public virtual DoctorTable DoctorTable { get; set; }
}

public partial class UserTable
{
    public int UserId { get; set; }
    public string UserName { get; set; }
    public string UserType { get; set; }
}
